name: Generate PDF

on:
  push:
    paths:
      - 'cv.html'
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate PDF
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          FILENAME="tboye-cv-${SHORT_SHA}.pdf"
          google-chrome --headless --no-sandbox --virtual-time-budget=5000 --print-to-pdf="$FILENAME" --no-margins --no-pdf-header-footer file://$PWD/cv.html
          echo "FILENAME=$FILENAME" >> "$GITHUB_ENV"

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: tboye-cv
          path: ${{ env.FILENAME }}
